runtime: nodejs20
env: standard
instance_class: F1
env_variables:
  NODE_OPTIONS: "--openssl-legacy-provider"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
