steps:
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    env:
      - 'NODE_ENV=development'
  
  - name: 'node:20'
    entrypoint: npm
    args: ['install', 'react-router@6.20.0', 'react-router-dom@6.20.0']
    
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'NODE_OPTIONS=--openssl-legacy-provider'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']